// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.yaio.core.node;

import de.yaio.core.node.BaseNode;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BaseNode_Roo_Configurable {
    
    declare @type: BaseNode: @Configurable;
    
}
