// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.yaio.core.node;

import javax.persistence.Entity;

privileged aspect SymLinkNode_Roo_Jpa_Entity {
    
    declare @type: SymLinkNode: @Entity;
    
}
