// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.yaio.app.core.node;

import javax.persistence.Entity;

privileged aspect EventNode_Roo_Jpa_Entity {
    
    declare @type: de.yaio.app.core.node.EventNode: @Entity;
    
}
