s/INSERT INTO PUBLIC.BASE_NODE \(DTYPE, SYSUID, NAME, PARENT_NODE, META_NODE_NUMMER, META_NODE_PRAEFIX, META_NODE_SUB_TYPE_TAGS, META_NODE_TYPE_TAGS, TYPE, CLASS_NAME, DOC_LAYOUT_TAG_COMMAND, DOC_LAYOUT_ADD_STYLE_CLASS, EBENE, IST_AUFWAND, IST_CHILDREN_SUM_AUFWAND, IST_CHILDREN_SUM_ENDE, IST_CHILDREN_SUM_STAND, IST_CHILDREN_SUM_START, IST_ENDE, IST_STAND, IST_START, IST_TASK, PLAN_AUFWAND, PLAN_CHILDREN_SUM_AUFWAND, PLAN_CHILDREN_SUM_ENDE, PLAN_CHILDREN_SUM_START, PLAN_ENDE, PLAN_START, PLAN_TASK, SORT_POS, STATE, SYS_CHANGE_COUNT, SYS_CHANGE_DATE, SYS_CREATE_DATE, SYS_CUR_CHECKSUM, RES_LOC_NAME, RES_LOC_REF, RES_LOC_TAGS, SYM_LINK_NAME, SYM_LINK_REF, SYM_LINK_TAGS, STAT_CHILD_NODE_COUNT, STAT_WORKFLOW_COUNT, STAT_WORKFLOW_TODO_COUNT, WORKFLOW_STATE, STAT_INFO_COUNT, STAT_URL_RES_COUNT, RES_CONTENTDMSID, RES_CONTENTDMSSTATE, RES_CONTENTDMSTYPE, RES_CONTENT_MIME, RES_CONTENT_SIZE, RES_INDEXDMSID, RES_INDEXDMSSTATE, RES_INDEXDMSTYPE, VERSION, NODE_DESC\) VALUES \('/    (CAST('/g
s/', /' as VARCHAR(255)), /g
s/, '/, CAST('/g
s/'\);\n\)/' as VARCHAR(6400000))\n)/g
s/null\);/null),/g
s/'\);/' as VARCHAR(6400000))),/g
