---------------------------
--- add constraints for parent
---------------------------
alter table BASE_NODE DROP CONSTRAINT FK_JYL61EY5OPRUI5UCIRG56R5N;
alter table BASE_NODE ADD CONSTRAINT FK_JYL61EY5OPRUI5UCIRG56R5N FOREIGN KEY(PARENT_NODE) REFERENCES PUBLIC.BASE_NODE(SYSUID) ON DELETE CASCADE;

---------------------------
--- delete some default-data
---------------------------
delete from BASE_NODE where SYSUID in ('SysPlay1', 'SysTest1', 'SysIntro1', 'SysStart1', 'SysRoad1', 'SysInfo1', 'SysHelp1', 'SysTempl1');

---------------------------
--- add basedata
---------------------------
MERGE INTO BASE_NODE USING
  (VALUES
  XXXSQLXXX
)
    AS vals(  DTYPE,
  SYSUID,
  NAME, PARENT_NODE,
  META_NODE_NUMMER, META_NODE_PRAEFIX, META_NODE_SUB_TYPE_TAGS, META_NODE_TYPE_TAGS,
  TYPE,
  CLASS_NAME,
  DOC_LAYOUT_TAG_COMMAND, DOC_LAYOUT_ADD_STYLE_CLASS,
  EBENE,
  IST_AUFWAND, IST_CHILDREN_SUM_AUFWAND, IST_CHILDREN_SUM_ENDE, IST_CHILDREN_SUM_STAND, IST_CHILDREN_SUM_START, IST_ENDE, IST_STAND, IST_START, IST_TASK,
  PLAN_AUFWAND, PLAN_CHILDREN_SUM_AUFWAND, PLAN_CHILDREN_SUM_ENDE, PLAN_CHILDREN_SUM_START, PLAN_ENDE, PLAN_START, PLAN_TASK,
  SORT_POS, STATE,
  SYS_CHANGE_COUNT, SYS_CHANGE_DATE, SYS_CREATE_DATE, SYS_CUR_CHECKSUM,
  RES_LOC_NAME, RES_LOC_REF, RES_LOC_TAGS,
  SYM_LINK_NAME, SYM_LINK_REF, SYM_LINK_TAGS,
  STAT_CHILD_NODE_COUNT, STAT_WORKFLOW_COUNT, STAT_WORKFLOW_TODO_COUNT,
  WORKFLOW_STATE,
  STAT_INFO_COUNT, STAT_URL_RES_COUNT,
  RES_CONTENTDMSID, RES_CONTENTDMSSTATE, RES_CONTENTDMSTYPE, RES_CONTENT_MIME, RES_CONTENT_SIZE, RES_INDEXDMSID, RES_INDEXDMSSTATE, RES_INDEXDMSTYPE,
  VERSION, NODE_DESC
  )
ON BASE_NODE.SYSUID = vals.SYSUID
WHEN NOT MATCHED THEN
INSERT (  DTYPE,
          SYSUID,
          NAME, PARENT_NODE,
          META_NODE_NUMMER, META_NODE_PRAEFIX, META_NODE_SUB_TYPE_TAGS, META_NODE_TYPE_TAGS,
          TYPE,
          CLASS_NAME,
          DOC_LAYOUT_TAG_COMMAND, DOC_LAYOUT_ADD_STYLE_CLASS,
          EBENE,
          IST_AUFWAND, IST_CHILDREN_SUM_AUFWAND, IST_CHILDREN_SUM_ENDE, IST_CHILDREN_SUM_STAND, IST_CHILDREN_SUM_START, IST_ENDE, IST_STAND, IST_START, IST_TASK,
          PLAN_AUFWAND, PLAN_CHILDREN_SUM_AUFWAND, PLAN_CHILDREN_SUM_ENDE, PLAN_CHILDREN_SUM_START, PLAN_ENDE, PLAN_START, PLAN_TASK,
          SORT_POS, STATE,
          SYS_CHANGE_COUNT, SYS_CHANGE_DATE, SYS_CREATE_DATE, SYS_CUR_CHECKSUM,
          RES_LOC_NAME, RES_LOC_REF, RES_LOC_TAGS,
          SYM_LINK_NAME, SYM_LINK_REF, SYM_LINK_TAGS,
          STAT_CHILD_NODE_COUNT, STAT_WORKFLOW_COUNT, STAT_WORKFLOW_TODO_COUNT,
          WORKFLOW_STATE,
          STAT_INFO_COUNT, STAT_URL_RES_COUNT,
          RES_CONTENTDMSID, RES_CONTENTDMSSTATE, RES_CONTENTDMSTYPE, RES_CONTENT_MIME, RES_CONTENT_SIZE, RES_INDEXDMSID, RES_INDEXDMSSTATE, RES_INDEXDMSTYPE,
          VERSION, NODE_DESC
)
  VALUES    vals.DTYPE,
    vals.SYSUID,
    vals.NAME, vals.PARENT_NODE,
    vals.META_NODE_NUMMER, vals.META_NODE_PRAEFIX, vals.META_NODE_SUB_TYPE_TAGS, vals.META_NODE_TYPE_TAGS,
    vals.TYPE,
    vals.CLASS_NAME,
    vals.DOC_LAYOUT_TAG_COMMAND, vals.DOC_LAYOUT_ADD_STYLE_CLASS,
    vals.EBENE,
    vals.IST_AUFWAND, vals.IST_CHILDREN_SUM_AUFWAND, vals.IST_CHILDREN_SUM_ENDE, vals.IST_CHILDREN_SUM_STAND, vals.IST_CHILDREN_SUM_START, vals.IST_ENDE, vals.IST_STAND, vals.IST_START, vals.IST_TASK,
    vals.PLAN_AUFWAND, vals.PLAN_CHILDREN_SUM_AUFWAND, vals.PLAN_CHILDREN_SUM_ENDE, vals.PLAN_CHILDREN_SUM_START, vals.PLAN_ENDE, vals.PLAN_START, vals.PLAN_TASK,
    vals.SORT_POS, vals.STATE,
    vals.SYS_CHANGE_COUNT, vals.SYS_CHANGE_DATE, vals.SYS_CREATE_DATE, vals.SYS_CUR_CHECKSUM,
    vals.RES_LOC_NAME, vals.RES_LOC_REF, vals.RES_LOC_TAGS,
    vals.SYM_LINK_NAME, vals.SYM_LINK_REF, vals.SYM_LINK_TAGS,
    vals.STAT_CHILD_NODE_COUNT, vals.STAT_WORKFLOW_COUNT, vals.STAT_WORKFLOW_TODO_COUNT,
    vals.WORKFLOW_STATE,
    vals.STAT_INFO_COUNT, vals.STAT_URL_RES_COUNT,
    vals.RES_CONTENTDMSID, vals.RES_CONTENTDMSSTATE, vals.RES_CONTENTDMSTYPE, vals.RES_CONTENT_MIME, vals.RES_CONTENT_SIZE, vals.RES_INDEXDMSID, vals.RES_INDEXDMSSTATE, vals.RES_INDEXDMSTYPE,
    vals.VERSION, vals.NODE_DESC
;
