// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.yaio.app.core.node;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EventNode_Roo_Configurable {
    
    declare @type: de.yaio.app.core.node.EventNode: @Configurable;
    
}
